{"ray": {"sid": "e76514f2c11a42a1ae493fa6a5db6ca7", "uid": null, "qid": "1d0a07e4a8cd4bc49c2093069e9e3eae", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [1d0a07e4a8cd4bc49c2093069e9e3eae]\nTraceback (most recent call last):\n  File \"C:\\Users\\avina\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openfabric_pysdk\\app\\worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 144, in execute\n    state['model_set'] = True\n    ~~~~~^^^^^^^^^^^^^\nTypeError: 'State' object does not support item assignment\n", "created_at": "2023-12-31T08:12:47.824674"}], "status": "FAILED", "created_at": "2023-12-31T08:12:46.443029", "updated_at": "2023-12-31T08:12:47.824674", "finished": true}, "in": {"text": ["string"]}, "out": {}}