{"ray": {"sid": "7c73d0c17eef4243a8e6fff1b582a48c", "uid": null, "qid": "1db9cb76e5f44961a83c7fadd515c218", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [1db9cb76e5f44961a83c7fadd515c218]\nTraceback (most recent call last):\n  File \"C:\\Users\\avina\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openfabric_pysdk\\app\\worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 60, in execute\n    response = agent.run(query)\n                         ^^^^^\nNameError: name 'query' is not defined\n", "created_at": "2023-12-29T18:34:13.439111"}], "status": "FAILED", "created_at": "2023-12-29T18:34:12.044387", "updated_at": "2023-12-29T18:34:13.439111", "finished": true}, "in": {"text": ["string"]}, "out": {}}