{"ray": {"sid": "84e950e528184603bd9445fb44e3b864", "uid": null, "qid": "a43df57d578b41e2860bf5b70df0b003", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [a43df57d578b41e2860bf5b70df0b003]\nTraceback (most recent call last):\n  File \"C:\\Users\\avina\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openfabric_pysdk\\app\\worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 220, in execute\n    agent_executor = get_model_state()\n                     ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 169, in get_model_state\n    agent = create_react_agent(llm, tools, prompt, output_parser=NewAgentOutputParser())\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: create_react_agent() got an unexpected keyword argument 'output_parser'\n", "created_at": "2023-12-30T14:14:09.143556"}], "status": "FAILED", "created_at": "2023-12-30T14:14:04.916822", "updated_at": "2023-12-30T14:14:09.143556", "finished": true}, "in": {"text": ["string"]}, "out": {"text": []}}