{"ray": {"sid": "e51ba15772e44959b4c0f9d260a2ee09", "uid": null, "qid": "b64daad9eab94e55ad6c306d14e81c87", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [b64daad9eab94e55ad6c306d14e81c87]\nTraceback (most recent call last):\n  File \"C:\\Users\\avina\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openfabric_pysdk\\app\\worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 144, in execute\n    if not \"model_set\" in state:\n           ^^^^^^^^^^^^^^^^^^^^\nTypeError: argument of type 'State' is not iterable\n", "created_at": "2023-12-31T08:17:49.031609"}], "status": "FAILED", "created_at": "2023-12-31T08:17:48.920296", "updated_at": "2023-12-31T08:17:49.034563", "finished": true}, "in": {"text": ["string"]}, "out": {}}