{"ray": {"sid": "b4389b26a9ef47328f3adffe45cbe3bf", "uid": null, "qid": "f255daf39cb04545ab1cd4b9062984b9", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [f255daf39cb04545ab1cd4b9062984b9]\nTraceback (most recent call last):\n  File \"C:\\Users\\avina\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\openfabric_pysdk\\app\\worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 131, in execute\n    agent_executor = get_model_state()\n                     ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\avina\\Downloads\\openfabric-ai-software-engineer 2\\openfabric-ai-software-engineer\\main.py\", line 121, in get_model_state\n    return agent_chain\n           ^^^^^^^^^^^\nNameError: name 'agent_chain' is not defined\n", "created_at": "2023-12-30T13:18:09.985783"}], "status": "FAILED", "created_at": "2023-12-30T13:18:06.687892", "updated_at": "2023-12-30T13:18:09.985783", "finished": true}, "in": {"text": ["string"]}, "out": {}}